remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Lab 9
description: In this lab we creaded a repository on GitHub. Worked through the Create a release base workbase course on GitHub.
